### ISSUE TITLE
Layout breaks on Firefox/Chrome when the browser dev tools are opened

### ISSUE THREAD

**Issue by chaoticgd** [fpclass/scratch-clone#3]
Steps to reproduce:
  - Open browser dev tools.
  - Configure dev tools to dock to the right.
  - Close dev tools.
  - Layout is borked.

GitHub doesn't seem to want to attach images so here's an Imgur link: https://i.imgur.com/bNHgWCP.png

**Comment by mbg** [comment]
Fixed by #4
